

"""
Django settings for ippe project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b!4vrb6ubhfv256+9ps69p_uz5s(&53xh@$=--wx77plppp41z'


INSTALLED_BASE = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

DEVELOP_APPS = [
    'apps.api',
    'apps.base',
    'apps.authenticate',
    'apps.elements',
    'apps.organizational',
    'apps.employees',
    'apps.sizes',
    'apps.requests',
    'apps.equipments',
    'apps.warehouses',
    'apps.inventories',
    'apps.assignments',
    'apps.reports',
    'apps.publications'
]

THIRD_APPS = [
    'debug_toolbar',
    'crispy_forms',
    'django_summernote',
    'notifications',
    'widget_tweaks',
    'import_export',
    'rest_framework', 
]

IMPORT_EXPORT_USE_TRANSACTIONS = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'

INSTALLED_APPS = INSTALLED_BASE + DEVELOP_APPS + THIRD_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}


ROOT_URLCONF = 'ippe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'ippe.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

X_FRAME_OPTIONS = 'ALLOWALL'
XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT', 'DELETE']


INTERNAL_IPS = [
    '127.0.0.1',
]


LOCALE_PATHS = (
    os.path.join(BASE_DIR, "authenticate/locale"), 
    os.path.join(BASE_DIR, "employees/locale"), 
    os.path.join(BASE_DIR, "equipments/locale"), 
    os.path.join(BASE_DIR, "inventories/locale"), 
    os.path.join(BASE_DIR, "organizational/locale"), 
    os.path.join(BASE_DIR, "reports/locale"), 
    os.path.join(BASE_DIR, "requests/locale"), 
    os.path.join(BASE_DIR, "sizes/locale"), 
    os.path.join(BASE_DIR, "warehouses/locale"), 
)

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish'))
)

LANGUAGE_CODE = 'en'

USE_I18N = True

USE_L10N = True

TIME_ZONE = 'America/New_York'

USE_TZ = True
SUMMERNOTE_THEME = 'bs4'

DJANGO_NOTIFICATIONS_CONFIG = { 'USE_JSONFIELD': True}
